# Generated by Django 5.0 on 2024-03-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_alter_product_unique_together_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
