# Generated by Django 5.0 on 2024-03-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0010_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
