# Generated by Django 5.0 on 2024-03-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0015_favori_sepet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepet',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sepet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favori',
        ),
        migrations.DeleteModel(
            name='Sepet',
        ),
    ]
