# Generated by Django 5.0 on 2024-03-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0017_favoriteitem_sepetitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteItem',
        ),
    ]
