# Generated by Django 5.0 on 2024-03-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0022_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
