# Generated by Django 5.0 on 2024-03-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_category_remove_urun_kategori_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
